name: trigger jenkins job
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      uses: appleboy/jenkins-action@master
      with:
        url: "http://54.179.173.106:8081/"
        user: "admin"
        token: "11628e4a93549b74b12d7069eef4966054"
        job: "test1"
